allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - icu-minify@4.13.2
  - next-intl-swc-plugin-extractor@4.13.2
  - next-intl@4.13.2
  - prettier@3.9.5
  - use-intl@4.13.2
