import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Hand-written (not `payload migrate:create`-generated): the CLI's
 * interactive rename-detection prompt ("is faq_items_rels created or
 * renamed from pages_blocks_faq_categories?") can't be resolved
 * non-interactively in this environment. The DDL below was derived by
 * copying this project's own established `_rels` polymorphic-relationship
 * table pattern (see payload_locked_documents_rels in
 * 20260710_100352_client_identity_map.ts) and the exact old table/enum
 * names from the migrations that created them
 * (20260724_115806_faq_items.ts, 20260724_115950_pages_faq_index_block.ts).
 * The accompanying .json snapshot was generated by scripted transform of
 * the previous snapshot, not by hand, to keep it structurally accurate.
 *
 * Replaces FaqItems' fixed `categories` select (company/vps/dedicated) and
 * the faq block's matching `categories` filter field with a single
 * polymorphic `pages` relationship on FaqItems (relationTo: service-pages,
 * pages) — editors tag a question with the actual page(s) it belongs to
 * instead of an abstract category, and it renders automatically wherever
 * tagged (see src/components/PageFaq.tsx).
 */
export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_faq_categories" DROP CONSTRAINT "pages_blocks_faq_categories_parent_fk";
  ALTER TABLE "service_pages_blocks_faq_categories" DROP CONSTRAINT "service_pages_blocks_faq_categories_parent_fk";
  ALTER TABLE "faq_items_categories" DROP CONSTRAINT "faq_items_categories_parent_fk";
  DROP TABLE "pages_blocks_faq_categories" CASCADE;
  DROP TABLE "service_pages_blocks_faq_categories" CASCADE;
  DROP TABLE "faq_items_categories" CASCADE;
  DROP TYPE "public"."enum_pages_blocks_faq_categories";
  DROP TYPE "public"."enum_service_pages_blocks_faq_categories";
  DROP TYPE "public"."enum_faq_items_categories";

  CREATE TABLE "faq_items_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"service_pages_id" integer,
  	"pages_id" integer
  );

  ALTER TABLE "faq_items_rels" ADD CONSTRAINT "faq_items_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."faq_items"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "faq_items_rels" ADD CONSTRAINT "faq_items_rels_service_pages_fk" FOREIGN KEY ("service_pages_id") REFERENCES "public"."service_pages"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "faq_items_rels" ADD CONSTRAINT "faq_items_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;

  CREATE INDEX "faq_items_rels_order_idx" ON "faq_items_rels" USING btree ("order");
  CREATE INDEX "faq_items_rels_parent_idx" ON "faq_items_rels" USING btree ("parent_id");
  CREATE INDEX "faq_items_rels_path_idx" ON "faq_items_rels" USING btree ("path");
  CREATE INDEX "faq_items_rels_service_pages_id_idx" ON "faq_items_rels" USING btree ("service_pages_id");
  CREATE INDEX "faq_items_rels_pages_id_idx" ON "faq_items_rels" USING btree ("pages_id");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "faq_items_rels" CASCADE;

  CREATE TYPE "public"."enum_pages_blocks_faq_categories" AS ENUM('company', 'vps', 'dedicated');
  CREATE TYPE "public"."enum_service_pages_blocks_faq_categories" AS ENUM('company', 'vps', 'dedicated');
  CREATE TYPE "public"."enum_faq_items_categories" AS ENUM('company', 'vps', 'dedicated');

  CREATE TABLE "pages_blocks_faq_categories" (
  	"order" integer NOT NULL,
  	"parent_id" varchar NOT NULL,
  	"value" "enum_pages_blocks_faq_categories",
  	"id" serial PRIMARY KEY NOT NULL
  );
  CREATE TABLE "service_pages_blocks_faq_categories" (
  	"order" integer NOT NULL,
  	"parent_id" varchar NOT NULL,
  	"value" "enum_service_pages_blocks_faq_categories",
  	"id" serial PRIMARY KEY NOT NULL
  );
  CREATE TABLE "faq_items_categories" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_faq_items_categories",
  	"id" serial PRIMARY KEY NOT NULL
  );

  ALTER TABLE "pages_blocks_faq_categories" ADD CONSTRAINT "pages_blocks_faq_categories_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages_blocks_faq"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "service_pages_blocks_faq_categories" ADD CONSTRAINT "service_pages_blocks_faq_categories_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."service_pages_blocks_faq"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "faq_items_categories" ADD CONSTRAINT "faq_items_categories_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."faq_items"("id") ON DELETE cascade ON UPDATE no action;

  CREATE INDEX "pages_blocks_faq_categories_order_idx" ON "pages_blocks_faq_categories" USING btree ("order");
  CREATE INDEX "pages_blocks_faq_categories_parent_idx" ON "pages_blocks_faq_categories" USING btree ("parent_id");
  CREATE INDEX "service_pages_blocks_faq_categories_order_idx" ON "service_pages_blocks_faq_categories" USING btree ("order");
  CREATE INDEX "service_pages_blocks_faq_categories_parent_idx" ON "service_pages_blocks_faq_categories" USING btree ("parent_id");
  CREATE INDEX "faq_items_categories_order_idx" ON "faq_items_categories" USING btree ("order");
  CREATE INDEX "faq_items_categories_parent_idx" ON "faq_items_categories" USING btree ("parent_id");`)
}
